image: archlinux
shell: true
sources:
  - git@git.sr.ht:~brodie/portfolio
tasks:
  - install-dependencies: |
      # Install micromamba.
      curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
      ./bin/micromamba shell -s posix hook >> ~/.buildenv

      # Install Poetry.
      curl -sSL https://install.python-poetry.org | python3 -
      echo 'export PATH="/home/build/.local/bin:$PATH"' >> ~/.buildenv

      # Source buildenv to access micromamba and Poetry in this session.
      . ~/.buildenv

      # Create the portfolio Mamba environment defined by environment.yml.
      cd portfolio
      micromamba create --file environment.yml --yes

      # Install Python dependencies.
      micromamba run --name portfolio poetry install

      # Export secrets.
      cat ~/.secrets >> ~/.buildenv
  - test: |
      cd portfolio
      micromamba activate portfolio
      git-crypt unlock ~/.git-crypt-key
      pytest
secrets:
  # SSH key.
  - bc3fa43b-fd2d-4681-8191-603226c49d44
  # ~/.secrets file.
  - be8c2a4b-d3a1-433f-affa-30fac28de317
  # ~/.git-crypt-key file.
  - c011ad6d-818b-4c35-a073-93ea32658da4
