# Mamba environment file.
name: portfolio
channels:
  - conda-forge
dependencies:
  # Match Lambda runtime's Python version.
  - python=3.9
  - git-crypt=0.7
  # Version 18 is active LTS: https://nodejs.org/en/about/releases/.
  - nodejs=18
