[tool.poetry]
name = "portfolio"
version = "0.1.0"
description = ""
authors = ["Brodie Blackburn <brodie.blackburn@gmail.com>"]

[tool.poetry.dependencies]
python = "~3.9"
requests = "^2.27.1"
beancount = "^2.3.5"
mechanicalsoup = "^1.1.0"
pyotp = "^2.6.0"
aws-cdk-lib = "^2.19.0"
playwright = "^1.28.0"
"aws-cdk.aws-lambda-python-alpha" = "^2.73.0-alpha.0"
datasette = "^0.64.2"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
pytest = "^7.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
update-balances = "portfolio.balances:update"
