[project]
name = "function"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "mangum>=0.17.0",
    "datasette>=0.64.2",
    "datasette-auth-github>=0.13.1",
    "datasette-redirect-forbidden>=0.1",
    "datasette-dashboards>=0.6.2",
    "datasette-hashed-urls>=0.4",
]
