name: deploy
on:
  push:
    branches:
      - master
  repository_dispatch:
    types:
      - portfolio-ledger-push
jobs:
  deploy-portfolio:
    runs-on: ubuntu-latest
    # Allows JWT to be requested from GitHub's OIDC provider.
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: eidorb/portfolio-ledger
          token: ${{ secrets.TOKEN }}
          path: portfolio-ledger
      - id: cache
        uses: actions/cache@v3
        with:
          # Use contents of Mamba environment file and Poetry lock file as cache key.
          key: ${{ hashFiles('environment.yml', 'poetry.lock') }}
          # Cache micromamba binary, .bashrc, Poetry installation and Mamba environment.
          path: |
            ./bin/micromamba
            ~/.bashrc
            ~/.local/bin/poetry
            ~/.local/share/pypoetry
            ~/micromamba/envs/portfolio
      - if: steps.cache.outputs.cache-hit != 'true'
        run: |
          # Install micromamba.
          wget -qO- https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
          ./bin/micromamba shell hook > ~/.bashrc

          # Install Poetry.
          curl -sSL https://install.python-poetry.org | python3 -

          # Create Mamba environment.
          source ~/.bashrc
          micromamba create --file environment.yml --yes
          micromamba activate portfolio

          # Install Python package dependencies.
          poetry install
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::961672313229:role/Account-GithubOidcRole20798CD3-LZP3AHTIPJU2
          aws-region: ap-southeast-2
      - run: |
          source ~/.bashrc
          micromamba activate portfolio

          # Unlock git-crypt.
          echo $GIT_CRYPT_KEY | base64 -d | git-crypt unlock -

          # Convert portfolio Beancount ledger to SQLite.
          bean-sql portfolio-ledger/portfolio.beancount portfolio/cdk/portfolio.db 2>/dev/null

          # Create target allocations table.
          sqlite3 portfolio/cdk/portfolio.db < portfolio-ledger/targets.sql

          # Initialise database with views.
          sqlite3 portfolio/cdk/portfolio.db < portfolio/cdk/views.sql

          # Bundle Lambda function dependencies.
          poetry run bundle-lambda-function

          # Install Node.js package dependencies.
          npm ci

          # Show CDK stack diff.
          npx cdk diff

          # Deploy CDK stack.
          npx cdk deploy --require-approval never
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
