name: test
on:
  # Schedule approximately fortnightly test runs.
  schedule:
    - cron: "0 0 1,15 * *"
  # Allow workflow to be run manually.
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Allows JWT to be requested from GitHub's OIDC provider.
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - id: cache
        uses: actions/cache@v4
        with:
          # Use contents of Mamba environment file, NPM lock file and Poetry lock file as cache key.
          key: ${{ hashFiles('environment.yml', 'package-lock.json', 'poetry.lock') }}
          # Cache micromamba binary, environments, and pipx installs.
          path: |
            ./bin/micromamba
            ~/micromamba/envs
            ~/.local/pipx
      # Assume role to read/write AWS parameter.
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::961672313229:role/Account-GithubOidcRole20798CD3-LZP3AHTIPJU2
          aws-region: ap-southeast-2
      - if: steps.cache.outputs.cache-hit != 'true'
        run: |
          # Install micromamba.
          wget -qO- https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
          ./bin/micromamba shell hook > ~/.bashrc

          # Install Poetry.
          pipx install poetry~=1.8

          # Create Mamba environment.
          eval "$(./bin/micromamba shell hook -s posix)"
          micromamba create --file environment.yml --yes
          micromamba activate portfolio

          # Install Python package dependencies.
          poetry install
      - run: |
          eval "$(./bin/micromamba shell hook -s posix)"
          micromamba activate portfolio

          # Unlock git-crypt.
          echo $GIT_CRYPT_KEY | base64 -d | git-crypt unlock -

          # Test
          pytest tests
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
